name: Release

on: workflow_dispatch
    
jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build --tag mtdev-api-image .
          docker save -o image-api.tar mtdev-api-image
      - name: copy image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: image-api.tar
          target: ~/containers/mtdev-api
            
  api-up:
    name: API Up
    needs: [deploy-api]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: load images and up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/containers/mtdev-api
            docker load -i image-api.tar
            docker-compose up -d
            rm image-api.tar
            docker system prune --all --volumes --force

